# Generated by Django 3.1.6 on 2021-03-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0004_auto_20210228_2135'),
        ('Account', '0003_user_verified_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verified_emails',
            new_name='credits',
        ),
        migrations.AddField(
            model_name='user',
            name='emails',
            field=models.ManyToManyField(to='Scraper.EmailModel'),
        ),
    ]
