# Generated by Django 3.1.6 on 2021-03-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_auto_20210303_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlypayment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='oneoffpayment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='specialpayment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='yearlypayment',
            name='amount',
        ),
        migrations.AlterField(
            model_name='amount',
            name='price',
            field=models.CharField(choices=[('1', 'Monthly Payment'), ('2', 'Yearly Payment'), ('3', 'One-off Payment'), ('4', 'Special Payment')], default='3', max_length=1),
        ),
    ]
