# Generated by Django 3.1.6 on 2021-02-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=225)),
                ('domain', models.URLField(blank=True, max_length=225)),
                ('verified', models.BooleanField(default=False)),
                ('position', models.CharField(blank=True, max_length=225)),
                ('country', models.CharField(blank=True, max_length=225)),
            ],
        ),
    ]
