# Generated by Django 3.1.6 on 2021-02-28 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmodel',
            name='company_names',
        ),
        migrations.RemoveField(
            model_name='scrapedlink',
            name='parent_link',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='EmailModel',
        ),
        migrations.DeleteModel(
            name='OdinList',
        ),
        migrations.DeleteModel(
            name='ScrapedLink',
        ),
    ]
