# Generated by Django 3.1.6 on 2021-02-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0002_auto_20210212_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(default='N/A')),
                ('last_scraped', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
