# Generated by Django 3.1.6 on 2021-02-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0003_company_emailmodel_odinlist_scrapedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedlink',
            name='link',
            field=models.URLField(default='N/A', max_length=500, unique=True),
        ),
    ]
