# Generated by Django 3.1.6 on 2021-02-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0004_emailmodel_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmodel',
            name='last_validated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scrapedlink',
            name='last_scraped',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
