# Generated by Django 3.1.6 on 2021-03-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0004_auto_20210228_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmodel',
            name='country',
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='department',
            field=models.CharField(default='N/A', max_length=225),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='email_type',
            field=models.CharField(choices=[('1', 'personal'), ('2', 'generic')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='linkedin',
            field=models.CharField(default='N/A', max_length=225),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=225),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='seniority',
            field=models.CharField(choices=[('1', 'junior'), ('2', 'senior'), ('3', 'executive')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='twitter',
            field=models.CharField(default='N/A', max_length=225),
        ),
        migrations.AddField(
            model_name='odinlist',
            name='country',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='odinlist',
            name='disposable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='odinlist',
            name='organization',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='odinlist',
            name='state',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='odinlist',
            name='webmail',
            field=models.BooleanField(default=False),
        ),
    ]
